d = {}
n = input("Enter the name: ")
m = input("Enter language")
d.update({n:m})
n = input("Enter the name: ")
m = input("Enter language")
d.update({n:m})
n = input("Enter the name: ")
m = input("Enter language")
d.update({n:m})
n = input("Enter the name: ")
m = input("Enter language")
d.update({n:m})
print(d)