marks = []
f1 = input("Enter mark 1: ")
f2 = input("Enter mark 2: ")
f3 = input("Enter mark 3: ")
f4 = input("Enter mark 4: ")
f5 = input("Enter mark 5: ")
f6 = input("Enter mark 6: ")
f7 = input("Enter mark 7: ")
marks.append(f1)
marks.append(f2)   
marks.append(f3)
marks.append(f4)
marks.append(f5)
marks.append(f6)
marks.append(f7)
print(marks)
