set = set()
num1 = int(input("Enter a number to add to the set: "))
num2 = int(input("Enter a number to add to the set: "))
num3 = int(input("Enter a number to add to the set: "))
num4 = int(input("Enter a number to add to the set: "))
num5 = int(input("Enter a number to add to the set: "))
num6 = int(input("Enter a number to add to the set: "))
num7 = int(input("Enter a number to add to the set: "))
set.add(num1)
set.add(num2)
set.add(num3)
set.add(num4)
set.add(num5)
set.add(num6)
set.add(num7)
print(set)